### ISSUE TITLE
Test mailing list signup

### ISSUE THREAD

**Issue by ikarth** [falonofthetower/howling-hematite#134]

**Comment by falonofthetower** [comment]
Technically the mailing list is tested. https://github.com/falonofthetower/howling-hematite/blob/master/spec/services/giver_donate_spec.rb#L46

I don't think I have a feature test for it, but it doesn't actually doing anything that feature can test (that I can think of) if we wanted to add something to "thank you" that mentions the mailing list that is possible.

**Comment by ikarth** [comment]
I guess we should make the production server live and see if we can sign up for the mailing list on that.

**Comment by falonofthetower** [comment]
It has a mailing list now. I setup a dummy account and it has worked when I tested it. You want to be careful though because it seems to reject multiple signups to the same email address in a short time so you can't just signup and then signup a second time.

**Comment by falonofthetower** [comment]
This has been tested so...
