### ISSUE TITLE
Change donation text fields

### ISSUE THREAD

**Issue by ikarth** [falonofthetower/howling-hematite#47]
Change the public name field to better reflect potential use for in memory of and similar uses.

Add a text field for people who want to send us a longer message or story. (Should this be a separate form/page?)

**Comment by falonofthetower** [comment]
No, we need to leave it at one page/form. Unless you don't want to tie the message to the donation.

**Comment by falonofthetower** [comment]
What name do we want to use? I just need to have the values for this to make it happen.

* Name of message

I take it back, a separate contact page is always a possibility--we need a decision here.

**Comment by falonofthetower** [comment]
Fixed https://github.com/falonofthetower/howling-hematite/pull/90
