### ISSUE TITLE
Donation telemetry from the server

### ISSUE THREAD

**Issue by ikarth** [falonofthetower/howling-hematite#50]
Need a way to get public donation information from the server:
Priority in order:
- Current Total Donations
- Current # of donors
- Donations at the start of today (or the period we're checking for)
- Historical information about donation amounts

Information will ideally be loaded via an XMLHttpRequest, should not be cross-domain, and can be in one of JSON, text, XML, csv, or tsv formats.

**Comment by falonofthetower** [comment]
* Donations at the start of today (or the period we're checking for)
* Historical information about donation amounts

You are going to need to define these

**Comment by falonofthetower** [comment]
https://github.com/falonofthetower/howling-hematite/pull/70
